### ISSUE TITLE
Requesting a CONTRIBUTING.md document

### ISSUE THREAD

**Issue by flimzy** [apache/couchdb-documentation#111]
As I'm finding myself contributing more and more PRs to this documentation, I wish I had some guidelines, other than the existing docs, for what's acceptable.

- How detailed should descriptions be?
- Are config options expected to always show default values? Or is any valid value permitted?
- Is it appropriate to retroactively update `whatsnew` documentation?
- (Where) should documentation changes be discussed before submitting a PR?

And I'm sure many more questions will come up.

Are these things documented somewhere? I'd be happy to turn them into a CONTRIBUTING.md document and submitting a PR. :)

**Comment by wohali** [comment]
I recommend you join the dev@couchdb.apache.org mailing list and post this question there, where it might get a bit more attention. (GH issues are brand new to CouchDB and aren't being watched carefully yet.) And it's probably the answer to your last question as well. :)

I'd love to review and help you merge a CONTRIBUTING.md once you've got the answers you need.
