### ISSUE TITLE
Link to couch_replicator_utils.erl in CouchDB Replication Protocol is broken

### ISSUE THREAD

**Issue by jjrodrig** [apache/couchdb-documentation#221]
The link to couch_replicator_utils.erl at [Generate Replication ID](https://github.com/apache/couchdb-documentation/blob/master/src/replication/protocol.rst#generate-replication-id) is pointing to https://git-wip-us.apache.org/repos/asf?p=couchdb.git;a=blob;f=src/couch_replicator/src/couch_replicator_utils.erl;h=d7778db;hb=HEAD that is currently broken. 
 
The new URL seems to be https://github.com/apache/couchdb/blob/master/src/couch_replicator/src/couch_replicator_ids.erl

**Comment by flimzy** [comment]
Thanks for reporting. Would you want to create a PR with the necessary change?

**Comment by flimzy** [comment]
Thanks for reporting. Would you want to create a PR with the necessary change?

**Comment by jjrodrig** [comment]
Ok. I'll prepare the PR.
