### ISSUE TITLE
/db/_design_docs is not documented

### ISSUE THREAD

**Issue by jjrodrig** [apache/couchdb-documentation#229]
The GET and POST /db/_design_docs is implemented in CouchDB 2.x and provides a mechanism for retrieving the list of design documents created in a DB. 

The endpoint is referenced in the 2.0.0  [release notes](http://docs.couchdb.org/en/2.1.1/whatsnew/2.0.html) and it is defined as similar to _all_docs endpoint

I've checked couchdb code and the implementation is based on the [_all_docs handler](https://github.com/apache/couchdb/blob/a0e08857dbfc4a5d941b7ec2e90457df1c87c38e/src/couch_mrview/src/couch_mrview_http.erl#L64)

**Comment by eiri** [comment]
If I remember correctly it was found to be broken, so no point to document it before someone fix it.

**Comment by jjrodrig** [comment]
I didn't find any reported issue on this. Do you have any reference to the problem?

**Comment by eiri** [comment]
It's in internal tracker, but in nutshell `endkey` + `limit` and `inclusive_end` not working as expected. I think I can glue together a test case and open gh issue for that.

**Comment by eiri** [comment]
Here we go: apache/couchdb#1100

**Comment by wohali** [comment]
Closed by #242.
