### ISSUE TITLE
seq_interval parameter for /db/_changes endpoint is not documented

### ISSUE THREAD

**Issue by jjrodrig** [apache/couchdb-documentation#230]
I've seen some interest in different CouchDB related projects in the use of seq_interval parameter for changes retrieval optimization.
Cloudant Sync - cloudant/sync-android#534
PouchDB - pouchdb/pouchdb#6643

I don't find the description of this parameter in the documentation. 

@willholley describes this parameter in this way: 
"The seq_interval parameter instructs Cloudant / CouchDB to skip generation of sequence numbers - i.e. return a seq for every N results. last_seq is always populated. When fetching changes in a batch, it should be possible to effectively set seq_interval=<batch size> to improve performance and reduce load on the remote database."

**Comment by wohali** [comment]
Draft text to include:

> When fetching changes in a batch, setting the seq_interval parameter tells CouchDB to only calculate the seq_interval with every Nth result returned. By setting `seq_interval=<batch size>`, where `<batch size>` is the number of results requested per batch, load can be reduced on the source CouchDB database; computing the seq value across many shards (esp. in highly-sharded databases) is expensive in a heavily loaded CouchDB cluster.

> Cloudant Sync and PouchDB already optimize this parameter by setting `seq_interval=<batch size>`.
  and increase throughput by reducing latency between sequential requests in bulk document transfers. This has resulted in up to a 20% replication performance improvement in the scenario previously described.

**Comment by nickva** [comment]
Great idea we should do this. We'd have to think how to do this in a backward compatible manner, that is handle the case were seq_interval is not supported.

**Comment by wohali** [comment]
@nickva Per the PouchDB bug linked above, `seq_interval` is ignored in 1.x.

I think your comment belongs over on apache/couchdb#1225 ? This is just documenting the already-in-place query parameter.

**Comment by nickva** [comment]
@wohali oops, totes belongs in the other issue, thanks!
