### ISSUE TITLE
Update documentation to describe queries support for /_all_docs

### ISSUE THREAD

**Issue by wohali** [apache/couchdb-documentation#233]
See apache/couchdb#1032 and apache/couchdb#820 for detail. There are new parameters for:

* `/{db}_all_docs`
* `/{db}/_design_docs`
* `/{db}/_local_doc`

Wait until apache/couchdb#1032 lands before merging any PR on this, please.

**Comment by jiangphcn** [comment]
can track with https://github.com/apache/couchdb-documentation/pull/241
