### ISSUE TITLE
"rewrite" documentation has confusing headings

### ISSUE THREAD

**Issue by nkronlage** [apache/couchdb-documentation#236]
http://docs.couchdb.org/en/2.1.1/api/ddoc/rewrites.html#rewrite-section-a-is-stringified-function

This page says 'Rewrite section a is stringified function'. Is that supposed to be 'Rewrite section is a stringified function'?

I'm also not sure what a 'section' is. Is that just the value of the rewrite field?

**Comment by johs** [comment]
http://docs.couchdb.org/en/2.1.1/api/ddoc/rewrites.html#rewrite-section-a-is-stringified-function
also says that "‘Rewrite using JS’ feature was introduced in CouchDB 1.7. " The feature prepared for, but not included in 1.7 
This should be:
‘Rewrite using JS’ feature was introduced in CouchDB 2.0.
