### ISSUE TITLE
Improve first-time install & setup

### ISSUE THREAD

**Issue by wohali** [apache/couchdb-documentation#273]
Needs a few hints after installation:

* Where is my data stored?
* Where are my log files?
* Where are various server-level settings stored / where should I edit?

with deltas for installing by package (and, maybe, using the Docker images, though this is still not recommended)

**Comment by bean5** [comment]
First-time setup could certainly be improved. Documentation seems out of date and makes it way more difficult than it should be.

See also:
* https://github.com/apache/couchdb-fauxton/issues/1276
* https://github.com/apache/couchdb-documentation/issues/539
* https://github.com/apache/couchdb-docker/issues/175

**Comment by bean5** [comment]
Documentation for Windows and macOS have more sections and are more fleshed out than the documentation for docker.

**Comment by wohali** [comment]
@bean5 Would you please stop spamming our issue tracker?

Yes, there is room for improvement, and we are a volunteer-run project. Creating 3-4 new issues and "shotgunning" responses across a large number of tickets isn't going to help.

Pull requests are welcome.

**Comment by bean5** [comment]
@wohali I didn't mean to shotgun. Each of those tickets made sense for the respective repository and I linked to them here because in my opinion (which might not be worth much) could collectively help out here.

I'm going to read your response at https://github.com/apache/couchdb-docker/issues/176 . Looks like you have some good information there. I look forward to reading it. I hope to contribute to the project soon (with PRs instead of discussion).

**Comment by bean5** [comment]
> ... maybe, using the Docker images, though this is still not recommended

@wohali Why is using a docker container not recommended?

**Comment by wohali** [comment]
@bean5 Long story short, performance impacts, especially with the CouchDB 2.x/3.x clustering code, though this view is not shared uniformly by the entire development team.

With CouchDB 4.0 changing the backend, deploying CouchDB with docker will be recommended (though FoundationDB should be installed on bare metal if possible.)

**Comment by janzheng** [comment]
the install instructions for debian 10 seem completely incorrect... sorry I don't know how to be more constructive, but I can't seem to get the right package installed

**Comment by wohali** [comment]
@janzheng We literally just updated the documentation yesterday for 3.1.1. Can you confirm you're using the latest approach? That should be

```
sudo apt update && sudo apt install -y curl apt-transport-https gnupg
curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | sudo tee /usr/share/keyrings/couchdb-archive-keyring.gpg >/dev/null 2>&1
source /etc/os-release
echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ ${VERSION_CODENAME} main" \
    | sudo tee /etc/apt/sources.list.d/couchdb.list >/dev/null
sudo apt update
sudo apt install -y couchdb
```

**Comment by wohali** [comment]
I've just tested the above and it works perfectly under `arm64` for 3.1.1.

We didn't introduce arm64 package support prior to 3.0.0, and we don't recommend running a 3.x release older than 3.1.1.

**Comment by janzheng** [comment]
thanks for the reply! I'm completely new to anything linux, arm, or couchdb, so I'm pretty fresh... 
I retried it and I got it working! This is probably obvious to someone who does this all day but I had to replace ` ${VERSION_CODENAME}` with `buster` and then also `apt install couch-libmozjs185-1.0` which I'm not sure what it does, but it removed a 500mb linux arm file as part of the install...

as for installing 3.1.1, if I follow the documentation, it should just install the latest (3.1.1) right?

Thanks so much for your help!!

**Comment by wohali** [comment]
@janzheng No need to change anything, the variable subtitution is automatic if you follow the previous line, as that sets the value of `${VERSION_CODENAME}` for you. But manually putting `buster` in there shouldn't cause any issue.

Yes, following those lines it will install the latest, which today is 3.1.1. It shouldn't have required you to install `couch-libmozjs185-1.0` as well, it should have done that automatically.

Looks like you are running this inside of Docker perhaps? If that's the case, no, you need to run the setup steps manually, as outlined, after starting the couchdb process.

But this is **way** outside of the scope of this ticket, which is laser focused on improving the documentation, and isn't the right place for bug reporting.

I'm going to mark these responses as off-topic. If you need more help please join our `couchdb.slack.com` instance, our `users@couchdb.apache.org` mailing list, or use the Discussions tab above to ask for general help.

**Comment by janzheng** [comment]
Sorry, I do have an update to https://docs.couchdb.org/en/stable/config/auth.html#config-admins: could you please add the location of the admin info which is now under `/opt/couchdb/etc`?

I'll come hang out in Slack, thanks!
