### ISSUE TITLE
Chapter 11.1.2. - The Cluster Setup Wizard - definition of "same install procedure"

### ISSUE THREAD

**Issue by ufobat** [apache/couchdb-documentation#325]
In Chapter 11.1.2 that explains how to use the Cluster Setup Wizard you can find following lines

> When you click “setup cluster” you are asked for admin credentials again and then to add nodes by IP address. To get more nodes, go through the same install procedure on other machines.

I am unsure what the term "same install procedure" exactly means. During my cluster setup I noticed that I had to run the wizard *only* on one of the 2 cluster nodes. Could you please explain/document exactly which steps should on each of the other maschines?

**Comment by wohali** [comment]
@ufobat the phrase "on other machines" should be replaced with "for each node, using the same machine to perform the setup process."

A pull request would be welcome :)
