### ISSUE TITLE
Update uuid config documentation

### ISSUE THREAD

**Issue by bleveque** [apache/couchdb-documentation#333]
I've been advised that all nodes in a cluster should be given the same UUID, but the description of the `uuid` setting in the [docs](http://docs.couchdb.org/en/2.2.0/config/couchdb.html#couchdb/uuid) leads me to believe that each node should have a unique uuid:
> Unique identifier for this CouchDB server instance.

It would also be helpful to have some information in the docs about how the UUID is used.

**Comment by wohali** [comment]
This happened in https://github.com/apache/couchdb-documentation/pull/356
