### ISSUE TITLE
Broken Links to wiki.apache.org

### ISSUE THREAD

**Issue by jjrodrig** [apache/couchdb-documentation#351]
Checking the doc I've noticed that all links to the content in the old wiki seems to be broken. 

Currently, there are the following references to the wiki.

```
src/ddocs/ddocs.rst:          <http://wiki.apache.org/couchdb/Formatting_with_Show_and_List#Showing_Documents>`_
src/ddocs/ddocs.rst:          <http://wiki.apache.org/couchdb/Formatting_with_Show_and_List#Listing_Views_with_CouchDB_0.10_and_later>`_
src/ddocs/ddocs.rst:          <http://wiki.apache.org/couchdb/Document_Update_Handlers>`_
src/ddocs/ddocs.rst:          <http://wiki.apache.org/couchdb/Replication#Filtered_Replication>`_
src/ddocs/ddocs.rst:          <http://wiki.apache.org/couchdb/Document_Update_Validation>`

src/install/unix.rst:    * `Installing CouchDB <https://cwiki.apache.org/confluence/display/COUCHDB/Installing+CouchDB>`_
src/replication/protocol.rst:* `CouchDB documentation <http://wiki.apache.org/couchdb/Replication>`_

```
In this situation could be better to remove them from the doc. 
There is any reason for keeping them in the doc?

**Comment by wohali** [comment]
@jjrodrig Good catch - we are indeed moving all of the old (ancient, really) wiki content into the docs proper, but haven't yet scrubbed the links back to the wiki from the docs.

Would you be so kind as to submit a PR removing these? Thanks!
