### ISSUE TITLE
purge_seq is number now

### ISSUE THREAD

**Issue by wohali** [apache/couchdb-documentation#364]
From apache/couchdb#1809 :+1: 

> According to the docs, purge_seq is still reported as a "number". Reality has it - it's now ( and probably other fields as well) are now "strings". This is probably related to the "Clustered purge" feature. IBM's cloudant-java client is currently the only maintained java client for couchdb, and it cannot properly work with db-info queries (by the look of the stacktrace, it also affects the lightcouch driver, meaning both of these drivers will fail to work.
> 
> This leaves the couchdb-java ecosystem in a problematic state for 2.3 and future releases.
> 
> While I opened this issue for the java driver, it will best to update the documentation for 2.3 and above release. and perhaps cover additional breaking changes.

/cc @jiangphcn

**Comment by jiangphcn** [comment]
thanks @wohali let me have PR for this

**Comment by jiangphcn** [comment]
PR https://github.com/apache/couchdb-documentation/pull/365
