### ISSUE TITLE
Confusing node name references in cluster setup section

### ISSUE THREAD

**Issue by j13k** [apache/couchdb-documentation#375]
I've just been through the process of setting up a CouchDB development cluster for the first time and got stuck for some time before realising that node names must be *FQDNs*.

The cluster setup documentation does indeed specify "IP or FQDN" in many of the examples, but to my mind, some references de-emphasise the need to use FQDNs for node names.

For example these blocks give the impression that simple hostnames might be sufficient in a local network:

https://github.com/apache/couchdb-documentation/blob/8655ee6ab97a7a8fccc584f6dbaf9866e5fa8c31/src/setup/cluster.rst#L261-L272

https://github.com/apache/couchdb-documentation/blob/8655ee6ab97a7a8fccc584f6dbaf9866e5fa8c31/src/setup/cluster.rst#L346-L357

In my case all nodes were connected to a Docker network, and `ping`-able by hostname within the network.

It was only on reading [an issue comment on the main GitHub project](https://github.com/apache/couchdb/issues/729#issuecomment-319408516) by @wohali that I realised my issue was with using the simple hostnames.

In particular, points 4 and 5 clarified the issue, so it might be good to emphasise these in the documentation:

> 4. If DNS is configured, use the FQDN only: -name couchdb@my.host.name.com
> 5. Tricks with /etc/hosts don't work as Erlang bypasses libresolv.

**Comment by wohali** [comment]
Good point, @j13k . We improved documentation on this a few times already:

* https://github.com/apache/couchdb/commit/f728209102a84d669f81431dea0bd0d60655a12f#diff-c650ac78e5abcd019f2a6e82a58d67cd
  * so when you're editing vm.args, unless you ignore the entire comment block, you should be well informed to use FQDNs or IP addresses only
* https://github.com/apache/couchdb-documentation/commit/0828bc505fe237fe17728cf7cca2c8518eb74989#diff-dde5904690a6ef02896e85f64a5bb253
  * http://docs.couchdb.org/en/latest/setup/cluster.html#make-couchdb-use-correct-ip-fqdn-and-the-open-ports specifically

but it looks like L261-272 and L346-357 need updating, too.

Are there any other specific parts of the document you think need updating to make this clearer? I thought the cluster setup page was pretty explicit, but if you managed to skip past that advice and configure it wrong, others might as well.

**Comment by j13k** [comment]
Thanks for responding so promptly! I did see those comments in the vm.args commit, but only after I'd resolved the issue! :(

Normally I would pay more attention to config file comments, however in this case I'd been using the official Docker image. Given that it encapsulates the node configuration via an ENV var, I didn't look closely at the config file, so missed out on the crucial info. (As an aside, I think there's a more general lesson in there for Docker users...) I think pulling up the comment docs into the main documentation should be sufficient.

**Comment by j13k** [comment]
Also, just noticed a reference to `nodename@hostname` in the vm.args file itself:

https://github.com/apache/couchdb/blob/master/rel/overlay/etc/vm.args#L14

So I think a general tightening up of nomenclature might help.
