### ISSUE TITLE
Document Mango string comparison and sorting behavior

### ISSUE THREAD

**Issue by natevw** [apache/couchdb-documentation#382]
In the Mango documentation, neither the [Condition Operators](https://docs.couchdb.org/en/2.3.0/api/database/find.html#condition-operators) section nor the [Sort Syntax](https://docs.couchdb.org/en/2.3.0/api/database/find.html#sort-syntax) section specify the treatment of strings as far as comparison and sorting behave.

For example, is any [normalization](https://en.wikipedia.org/wiki/Unicode_equivalence) performed on the strings when comparing equality? Does string sorting follow the [Unicode Collation Algorithm](http://unicode.org/reports/tr10/), or simply a binary sort on either [code units](https://stackoverflow.com/a/27331885/179583) or code points, or something else (e.g. byte-by-byte sort on a UTF-8 encoding)?

**Comment by nono** [comment]
I hope that https://github.com/apache/couchdb-documentation/pull/448 answers this question.

**Comment by wohali** [comment]
Thanks @nono , closing. If there's still an issue @natevw , please ask to reopen.

**Comment by natevw** [comment]
I think that cross-reference suffices, appreciate it!
