### ISSUE TITLE
Broken cross-reference in [cluster] configuration

### ISSUE THREAD

**Issue by natevw** [apache/couchdb-documentation#383]
In the `q` part of the "Configuring Clustering" documentation page (<https://docs.couchdb.org/en/2.3.0/config/cluster.html#cluster/q>) there is a note "The value of q can also be overridden on a per-DB basis, at DB creation time." followed by a "See also" callout.

The contents of that call-out are broken, and do not link to anything. Instead the box literally says:

> httpdomain:put:PUT /{db} </{db}>

(Compare to the `placement` section where a nice link to "Placing a database on specific nodes" is provided in a similar callout.)

**Comment by wohali** [comment]
Thanks for all the bug reports, @natevw. Pull requests encouraged and welcome!
