### ISSUE TITLE
behaviour of new_edits=false is not well documented

### ISSUE THREAD

**Issue by ondra-novak** [apache/couchdb-documentation#390]
I often must deeply explain to other users, how new_edits works, how to use it (or why to not use it). The new_edits flag is mentioned along with _bulk_docs without any description or link to an appropriate section

## Possible Solution

* Describe that new_edits=false has purpose for replication only. There should be link to the section 2.4.2.5.2 where replication is documented
* Describe format of the document, when new_edits is set to false. It should mention that document must include the key "_revisions" otherwise bad things may happen.
 * There is mention about the key "_revisions" in the section "2.4.2.5.2. Upload Batch of Changed Documents", but the format of the key is not documented.  There should be a link to the section "2.18. Returned CouchDB Document with Revision Info". 
* It may be a good idea to describe, how _revisions is used to connect history of the document updates and when the conflict may happen. It may help to user to understand purpose of this field and why its presence is mandatory.

**Comment by zim32** [comment]
So I am here and readings this, this means I spend a lot of hours to figure out the problem, but it could be easily fixed (small documentation change). Is it very hard to fix the docs? Or this project is dead (like many others open source projects)?

**Comment by wohali** [comment]
Pull requests welcome, @zim32 .

**Comment by zim32** [comment]
The problem is I am not sure about this issue. My real issue is with PouchDB

**Comment by wohali** [comment]
We are not responsible for PouchDB - you'll have to speak to them about that.
