### ISSUE TITLE
Are _find API docs missing an entry for conflicts key?

### ISSUE THREAD

**Issue by j13k** [apache/couchdb-documentation#391]
I've successfully followed the docs to use a Mango query to scan for conflicted documents:

https://docs.couchdb.org/en/latest/replication/conflicts.html#finding-conflicted-documents-with-mango

However I've noticed that the example query includes a `conflicts` boolean key, which isn't mentioned in the `_find` API docs:

https://docs.couchdb.org/en/latest/api/database/find.html#db-find

Is this an omission? If so, I'm happy submit a patch for the docs, but what would be a good description for the key?

**Comment by wohali** [comment]
@j13k Indeed that's an omission, and a PR is welcome. Why not propose some text and @flimzy and I can review?
