### ISSUE TITLE
Is a 2.x homebrew formula still expected?

### ISSUE THREAD

**Issue by scottohara** [apache/couchdb-documentation#411]
In the [Installation on macOS](https://github.com/apache/couchdb-documentation/blob/master/src/install/mac.rst) docs, the following paragraph has been present since 9 September, 2016:

> The Homebrew build of CouchDB 2.x is still in development. Check back often for updates.

After almost three years, should macOS users still be advised to "check back often for updates", or is the possibility of a 2.x formula unlikely at this point?

I'm aware that there is the option to `brew cask install apache-couchdb`, which is an alternative method of manually installing the GUI version of `Apache CouchDB.app`.
However this yields a different experience to anyone previously using `brew install couchdb` for 1.x  (for example, it doesn't automatically link a `/usr/local/bin/couchdb` command, which some build/test scripts may be expecting).

Should the 2.x macOS install docs be updated to either:
1. remove the "Installation with Homebrew" section entirely?
2. instruct users to `brew install cask apache-couchdb` instead?
3. keep the existing "check back often for updates" text?

**Comment by big-r81** [comment]
It's in the pipeline as PR https://github.com/Homebrew/homebrew-core/pull/43478

**Comment by janl** [comment]
This landed, thanks @big-r81! https://github.com/Homebrew/homebrew-core/pull/46405
