### ISSUE TITLE
What are valid node names?

### ISSUE THREAD

**Issue by flimzy** [apache/couchdb-documentation#421]
It might be nice to add to the "add a node" documentation, the limitations on node names.

I imagine it's the same limitation as for valid Erlang node names, which I believe is a subset of valid DNS names, but I'm not sure, and I'm not finding a definitive answer in the CouchDB docs, or on the web at large.

If it's already in our docs, it should probably be made more prominent with some links from other relevant sections.

If it's not, and someone can point me to the right limitations, I'd be happy to write up the blurb and create a PR with the relevant details.

**Comment by wohali** [comment]
Indeed a node name comes from an Erlang node name.

The best documentation out there is here:

https://github.com/apache/couchdb/blob/master/rel/overlay/etc/vm.args#L13-L37

Feel free to copy this verbatim into the docs, it's not changed in a long while.

**Comment by wohali** [comment]
This is documented in https://docs.couchdb.org/en/stable/setup/cluster.html clearly now, closing.
