### ISSUE TITLE
couchdb.org points to the wrong place

### ISSUE THREAD

**Issue by euler0** [apache/couchdb-documentation#449]
`Download CouchDB` points `http://couchdb.org/#download`. But `couchdb.org` looks broken.

Is this temporary? Or should we replace the link with `http://couchdb.apache.org/#download`?

**Comment by wohali** [comment]
Temporary breakage, now that couchdb.org has been handed over to the Apache Software Foundation.

Paging @janl  (note - Jan is on holiday and won't be able to help with this for a bit)

**Comment by euler0** [comment]
@wohali Thanks for the information!

**Comment by andywenk** [comment]
I filed an ASF Infra ticket. It should be changed soon
