### ISSUE TITLE
apt-key needs sudo

### ISSUE THREAD

**Issue by axkibe** [apache/couchdb-documentation#450]
https://docs.couchdb.org/en/master/install/unix.html

At 1.1.1.2 . Installing the Apache CouchDB packages
Debian/Ubuntu: 

```
$ apt-key adv --keyserver keyserver.ubuntu.com --recv-keys \
 8756C4F765C9AC3CB6B85D62379CE192D401AB61
```

should be
```
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys \
  8756C4F765C9AC3CB6B85D62379CE192D401AB61
```

Thanks for the packages, just wondering why they aren't in the debian repository themselves.

**Comment by wohali** [comment]
Thanks for the pointer! Do you want to make a PR against the docs to fix this issue?

Unfortunately the packages violate a number of Debian-specific packaging requirements (mostly around de-bundling dependencies we have on various libraries, and shipping all of those as separate pacakges) that we can't easily resolve without a massive amount of work.

**Comment by axkibe** [comment]
If possible I prefer not to make a PR if it's okay, as I'd have to fork, clone, push, etc.

**Comment by wohali** [comment]
@axkibe No problem! In case you ever change your mind, CouchDB is always looking for new contributors.

I'll take care of it.

**Comment by axkibe** [comment]
Haha, Thanks :) Well first I need to start to be using it (switching over from mongoDB here)
