### ISSUE TITLE
Add a note about impossibility of manual migration of views from 1.x to 3.x  

### ISSUE THREAD

**Issue by eiri** [apache/couchdb-documentation#461]
Once we have a draft for Changelist in 3.0 we'll need a note in **Upgrade** section that it is 
impossible to upgrade index from 1.x to 3.x by just moving and renaming a file, i.e. the index need to be rebuild. The migration of indices from 2.x to 3.x should be automatic and transparent. 

Ref: https://github.com/apache/couchdb/pull/2324

**Comment by wohali** [comment]
@eiri thanks for this. Jan has just removed couchup mentions in #467 and stated you must "hop through" 2.x to get to 3.x from 1.x. Do you think this meets our needs?

**Comment by eiri** [comment]
Yes this is a great idea for the migration approach and should be sufficient for a transparent view conversion.

**Comment by wohali** [comment]
Great! I'll close this issue then as fixed by #467 .
