### ISSUE TITLE
Update scheduler docs/info endpoint docs with newly provided field info

### ISSUE THREAD

**Issue by wohali** [apache/couchdb-documentation#477]
As implemented by https://github.com/apache/couchdb/pull/2292 .

Ticket contains sample doc output which should make this go a lot faster.

**Comment by nickva** [comment]
I think this commit updated the example already? 

https://github.com/apache/couchdb-documentation/commit/051acd9c470ee1d7c5be280dc88d895ccf7fbb96

**Comment by wohali** [comment]
ok thanks! I would rather over-file these issues and have some duplicates than miss stuff for 3.0. :)
