### ISSUE TITLE
Document the need for 3.0 admin user after UNIX install

### ISSUE THREAD

**Issue by wohali** [apache/couchdb-documentation#501]
c.f. https://github.com/apache/couchdb/issues/2623 - our UNIX install guide needs to explicitly call out the 3.0 change for a mandatory admin user before startup will work.

**Comment by natcohen** [comment]
Added https://github.com/apache/couchdb-documentation/pull/502 but only to RedHat/CentOS since I don't know the behaviour for the other Unix OS

**Comment by dalthviz** [comment]
Hi, maybe it could be nice to add at the beginning of the installation docs a note explaining that starting from 3.0 you need to setup an admin user? Also, maybe the package configuration process should describe this and don't let the option to do the setup without giving a password for an admin (in the case of Ubuntu 16.04 and 18.04 you can do that and end up trying to figure out why the couchdb service doesn't start or work):

![image](https://user-images.githubusercontent.com/16781833/80494449-48225f80-892c-11ea-83b8-0bdfc25d3377.png)

**Comment by wohali** [comment]
Hello @dalthviz ,

The Debian/Ubuntu package intentionally allows this, in case you use alternative means to create the admin user. We don't want to make the password creation mandatory at this step, otherwise other people's workflows may break.

This matches other DB install experiences in Debian, such as MySQL or PostgreSQL.

**Comment by wohali** [comment]
@dalthviz Yup, that's coming in just a few moments.

Thanks for the reminder on this ticket! It had actually slipped past my radar.

**Comment by dalthviz** [comment]
Awesome :) , no problem :+1:
