### ISSUE TITLE
Extend Clouseau(search-plugin) installation docs

### ISSUE THREAD

**Issue by chintan-mishra** [apache/couchdb-documentation#511]
Clouseau(search-plugin) installation [docs](https://docs.couchdb.org/en/master/install/search.html#installation-of-binary-packages) are missing some steps that would allow basic usage by someone new to this plugin. While installing the plugin, we have to provide Java classpath for the plugin application to find all the dependencies and start all the components. However, best strategies to do so are missing.

## Expected Behavior

It was expected that Clouseau(search-plugin) would start. But instead, an error was shown.

## Current Behavior

While trying to start the Clouseau application following error is shown `Error: Could not find or load main class com.cloudant.clouseau.Main`

## Possible Solution

Add more details for the users to debug without pestering the devs and maintainers. Guide me. I will report my findings.

## Steps to Reproduce (for bugs)

<details>
<summary>
Series of commands that were executed on the host and inside the couchdb:3.0.0 container image.
</summary>

### Commands that were executed on the container host.
```bash
$ podman run --name relax -p 5984:5984 -d -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password couchdb
$ podman exec -it relax bash
```
### Commands that were run inside the container
```bash
# Download AdoptOpenJDK 8
curl -OL https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u242-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u242b08.tar.gz
# Extract the files
tar -xf OpenJDK8U-jdk_x64_linux_hotspot_8u242b08.tar.gz
# Move the files to suitable location
mv ./jdk8u242-b08 /usr/local/bin/
# Add them to environment
echo -e 'export PATH=/usr/local/bin/jdk8u242-b08/bin:$PATH' >> ~/.bashrc 
# Make it available in existing terminal instance
source ~/.bashrc
# Create folders for storing all Clouseau-related files
mkdir /opt/couchdb/extras
mkdir /opt/couchdb/extras/search
# Create the necessary files
# `clouseasu.ini`
cat > /opt/couchdb/extras/clouseau.ini << EOF
[clouseau]
; the name of the Erlang node created by the service, leave this unchanged
name=clouseau@127.0.0.1
; set this to the same distributed Erlang cookie used by the CouchDB nodes
cookie=monster
; the path where you would like to store the search index files
dir=/opt/couchdb/extras/search
; the number of search indexes that can be open simultaneously
max_indexes_open=500
EOF
# `log4j.properties`
cat> /opt/couchdb/extras/log4j.properties << EOF
log4j.rootLogger=debug, CONSOLE
log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} %c [%p] %m%n
EOF
# Fetch a release of Clouseau from GitHub
curl -OL https://github.com/cloudant-labs/clouseau/releases/download/2.17.0/clouseau-2.17.0-dist.zip
# Move it to the newly created directory
mv clouseau-2.17.0-dist.zip /opt/couchdb/extras
# After generous help from the user 'rnewson' on Slack. Added these steps
apt-get update && \
apt-get install unzip && \
unzip /opt/couchdb/extras/clouseau-2.17.0-dist.zip &&\ # Extract Clouseau
cd /opt/couchdb/extras/ && \
mv clouseau-2.17.0 clouseau
# Start the Clouseau application
java -server \
     -Xmx2G \
     -Dsun.net.inetaddr.ttl=30 \
     -Dsun.net.inetaddr.negative.ttl=30 \
     -Dlog4j.configuration=file:/opt/couchdb/extras/log4j.properties \
     -XX:OnOutOfMemoryError="kill -9 %p" \
     -XX:+UseConcMarkSweepGC \
     -XX:+CMSParallelRemarkEnabled \
     -cp /opt/couchdb/extras/clouseau:/opt/couchdb/extras/clouseau/lib/* \ # zip file and extracted directory were passed individually to test the issue
     com.cloudant.clouseau.Main \
     /opt/couchdb/extras/clouseau.ini
```
</details>

## Context

The purpose of this task was to start Clouseau(search-plugin) in the same container as the CouchDB. This would further allow building a CouchDB container image with all the benefits provided by Clouseau.

## Your Environment

* Version used: 3.0.0 tagged container image retrieved from docker.io/library/couchdb
* Browser Name and version: NA
* Operating System and version (desktop or mobile): OS - Fedora 31 | Kernel - 5.5.10-200.fc31.x86_64
* Link to your project: https://gitlab.com/rebhu-computing/rosf/sushrut.codes/cdtf

**Comment by chrystalcastillochavez** [comment]
I don't know about this

**Comment by chintan-mishra** [comment]
@chrystalcastillochavez 
What will help figure out a solution for this?

**Comment by chintan-mishra** [comment]
https://github.com/apache/couchdb/issues/2630
#516 
The referenced issues and this one are related.

**Comment by wohali** [comment]
@kocolosk @rnewson can one of you ehlp with this and/or #516 ? Would be nice to get this in for 3.0.1 / 3.1.0.

**Comment by bpluly** [comment]
The classpath depends on which way you use couchdb/clouseau, if you use docker and the jar at https://github.com/kocolosk/clouseau-docker, thanks to https://app.slack.com/team/UKRSK0L5A for pointing that out then the classpath is part of the exec script.

But if you just grab the cloudant release jar the script assumes that the classpath is already defined.
As all of the dependencies are in the same directory the classpath should be
   ` -classpath '/opt/clouseau/*'`

If you installed clouseau in /opt/clouseau

The parameters used for the server are not at all optimal, for instance max memory should be restricted to no more than a third of the memory arena. Thank you couchdb for making me dredge up ancient Lucence-fu.

For those interested my current server parameters are:

`java -server \                                                                                                                                        -verbose:jni \                                                                                                                                   -Xmx1G \                                                                                                                                         -Dsun.net.inetaddr.ttl=30 \                                                                                                                      -Dsun.net.inetaddr.negative.ttl=30 \                                                                                                             -Dlog4j.configuration=file:/opt/clouseau/log4j.properties \                                                                                      -XX:OnOutOfMemoryError="kill -9 %p" \                                                                                                            -XX:+UseConcMarkSweepGC \                                                                                                                        -XX:+CMSParallelRemarkEnabled \                                                                                                                  -classpath '/opt/clouseau/*' \                                                                                                                    com.cloudant.clouseau.Main \                                                                                                                     /opt/clouseau/clouseau.ini                                                                                                                                                                                                                                                                `

**Comment by bpluly** [comment]
To fix the documentation take the sentence, 

The files in each release should be unpacked into a directory on the Java classpath.

And add after it.

If you do not have a classpath already set, then add the line

`-classpath '/path to clouseau/* `

to the server command below.

**Comment by bpluly** [comment]
If clouseau is the only java service running on a box having a general CLASSPATH environment variable is not (IMO) good practice.

**Comment by wohali** [comment]
@bpluly Would you be willing to submit a PR with this valuable information? We'd certainly take it!

**Comment by bpluly** [comment]
If clouseau is the only java service running on a box having a general CLASSPATH environment variable is not (IMO) good practice.

> 
> 
> @bpluly Would you be willing to submit a PR with this valuable information? We'd certainly take it!

Sure. I'll do it during today.

**Comment by bpluly** [comment]
> 
> 
> @bpluly Would you be willing to submit a PR with this valuable information? We'd certainly take it!

Sure. I'll do it during today.

**Comment by Dracoyodan** [comment]
I added the classpath line in bpluly's comment above and still receive this error

**Comment by bpluly** [comment]
Where did you install clouseau, and what are the permissions and ownership
for the directory and files?

**Comment by Dracoyodan** [comment]
I unpacked the .zip file into /opt/
and I have changed ownership of the /opt/cloudeau/ directory and everything in it to my user:group

**Comment by bpluly** [comment]
Create the system user account clouseau and make that the owner of the
directory and files. You'll have to start it as sudo -u clouseau from the
console. That makes it easier to run as a service later, I have it running
under systemd for that. If I get chance today I'll glue together some notes.

They wouldn't be suitable in the main documentation they'd be more of a
HOWTO.

**Comment by Dracoyodan** [comment]
I created the user clouseau, and then transferred ownership of the clouseau folder and all of its contents to that user.
I switched to that user (by other means, the -u flag didn't work for me on Ubuntu) and ran the java command above, but got the same result.

```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Error: Could not find or load main class com.cloudant.clouseau.Main
Caused by: java.lang.ClassNotFoundException: com.cloudant.clouseau.Main

```

**Comment by bpluly** [comment]
You need to use nothing later than JDK 8.
Sorry the email of comments doesn't include block code.

S

**Comment by Dracoyodan** [comment]
Ah. I believe that is the issue.
Thank you

**Comment by subgero** [comment]
Hi @Dracoyodan, are you running this in a docker container? If I follow [this documentation](https://docs.couchdb.org/en/master/install/search.html#install-search) working on Ubuntu 18.04 everything works fine, but If I try to do the same in a docker container(apache/couchdb:3.1 | Debian 10), I receive this message:

`2020-06-23 05:54:05,939 clouseau.main [FATAL] Uncaught exception: Connection refused
2020-06-23 05:54:05,942 scalang.epmd.EpmdHandler [DEBUG] Oh snap channel closed.`  

- Jar files are in place /opt/clouseau, the same for clouseau.ini and log4j.properties.

- Dockerfile

> FROM apache/couchdb:3.1
expose 5984:5984
RUN apt update
RUN apt install libterm-readline-gnu-perl dialog -y
RUN apt upgrade -y
RUN apt install wget software-properties-common -y
RUN wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add -
RUN add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
RUN apt update
RUN apt install adoptopenjdk-8-hotspot -y
COPY src/clouseau/ /opt/clouseau/

- Inside the container we are running this:

`java -server -classpath '/opt/clouseau/*' -Xmx2G -Dsun.net.inetaddr.ttl=30 -Dsun.net.inetaddr.negative.ttl=30 -Dlog4j.debug=true -Dlog4j.configuration=file:/opt/clouseau/log4j.properties -XX:OnOutOfMemoryError="kill -9 %p" -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled com.cloudant.clouseau.Main /opt/clouseau/clouseau.ini
`

But I have no success.

**Comment by wohali** [comment]
Does this help?

https://github.com/apache/couchdb-docker/blob/4482af7b3504c2edf717540033111b5a270b391b/clouseau-compose/README.md

We haven't merged this documentation improvement yet.

**Comment by subgero** [comment]
@wohali Thank you very much, It is working now. 

It is only necessary to update docker-compose to 1.26.0 version. And I'd like to suggest, use the /opt/clouseau/ directory instead of /app/ according to the couchdb documentation.
