### ISSUE TITLE
Update _users security documentation to account for _security changes, "mandatory" fields

### ISSUE THREAD

**Issue by dholth** [apache/couchdb-documentation#513]
The _users documentation at https://docs.couchdb.org/en/stable/intro/security.html?highlight=org%20couchdb%20users#authentication-database is out of date.

"Users may only access (GET /_users/org.couchdb.user:Jan) or modify (PUT /_users/org.couchdb.user:Jan) documents that they own"

Technically true but the default 3.0 _security setting means users may not access or modify their own documents. Documentation should mention the _security and config settings to make this true.

(in my application the ideal would be read-only access to your own _user object)

"Each CouchDB user is stored in document format. These documents contain several mandatory fields, that CouchDB needs for authentication:

AFAICT some of these fields are not mandatory. derived_key, password_sha, password_scheme, salt are not needed when using proxy authentication. Can roles be missing too?

References apache/couchdb#2730 apache/couchdb#2734

**Comment by dholth** [comment]
In my testing an empty members array is enough to restore the 2.0 behavior. `{'members': {'roles': []}, 'admins': {'roles': ['_admin']}}`

**Comment by hawkrdg** [comment]
try setting this in local.ini, restart server, then fauxton as admin and clear the security for _users

[purge]
users_db_security_editable = true

**Comment by dholth** [comment]
It belongs in the couchdb section. This ini was wrong in the first release.

**Comment by papswell** [comment]
Hi, sorry to reopen this, 

I was finally able to get my config of CouchDB 3 work when i saw your [precious comment](https://github.com/apache/couchdb/issues/2881#issuecomment-627432875) :

> it is **not** a bad practice to alter the `_users` database security object - it is encouraged

So, thank you :)

But as i understand, the docs states the [exact opposite](https://docs.couchdb.org/en/latest/config/couchdb.html#couchdb/users_db_security_editable) ! 

Is there something i'm misunderstanding, or does it need to be fixed ? 
Let me know if i can help in any way

**Comment by dholth** [comment]
It does seem like the docs plan for 4.0 is to remove the 2.0 behavior "users can read their own user objects". If that happens I'd have to implement similar functionality in a web service, since that is how users find the database i want them to talk to.

**Comment by tommikarkkainen** [comment]
I started to change the intro/security document to implement these changes. I'm going to mention that the default settings prevent users from accessing any documents in the `_users` database, and that the setting can be changed but it is not recommended.

How do people feel about section [1.5.2.4. Users Public Information](https://docs.couchdb.org/en/stable/intro/security.html#users-public-information)? Accessing the public fields mentioned in this section would require a settings change that isn't recommended, and I don't think the Introduction part of the docs is the place to highlight something like that. Easiest solution is to remove that entire subsection.

**Comment by wohali** [comment]
Closed by #630. Thanks @tommikarkkainen !
