### ISSUE TITLE
Improvement to "3.1.2.2. Reduce and Rereduce Functions" argument description

### ISSUE THREAD

**Issue by toyssamurai** [apache/couchdb-documentation#517]
Currently, under **3.1.2.2. Reduce and Rereduce Functions**, the description of the _keys_ argument is:

`Array of pairs of docid-key for related map function results. Always null if rereduce is running (has true value).`

## Expected Behavior
The description gives an impression that the value of the _keys_ argument would look like this:

`[ ["docid1", "key1"], ["docid2", "key2"] ... ]`

## Current Behavior
What I actually see is: 

`[ ["key1", "docid1"], ["key2", "docid2"] ... ]`

## Possible Solution
I think that it would be less confusing if the documentation says **key-docid** instead of **docid-key** or, better yet, gives an example of what the value of the _keys_ argument would look like.

**Comment by wohali** [comment]
@toyssamurai Hey, thanks for this! This would be a very fast Pull Request, if you'd like to contribute the fix yourself. We'd certainly welcome the fix!
