### ISSUE TITLE
Continuous _changes and limit?

### ISSUE THREAD

**Issue by ronag** [apache/couchdb-documentation#545]
When using the "limit" parameter with a continous change feed. How does the server indicate the the feed has completed? Or is it up to the user to count the number of changes received and close the connection? If so, is there any advantage of using the limit parameter over simply terminating the connection?

**Comment by wohali** [comment]
Hey @ronag,

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)

We're happy to take a PR against the docs with the answer to the question(s) you've asked once you have a good answer.
