### ISSUE TITLE
persistent connection timeout?

### ISSUE THREAD

**Issue by ronag** [apache/couchdb-documentation#546]
At which point does couchdb close inactive persistent connections when using keep-alive?

**Comment by wohali** [comment]
Hey @ronag,

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)

We're happy to take a PR against the docs with the answer to the question(s) you've asked once you have a good answer.
