### ISSUE TITLE
Replicator database configuration parameters do not include max_history

### ISSUE THREAD

**Issue by wlthomson** [apache/couchdb-documentation#552]
CouchDB 3.1 replication seems to support `max_history` as a configurable parameter (see [couch_replicator_scheduler#L238](https://github.com/apache/couchdb/blob/4e64f5b492990b03f7f58a47ec173d048a3f381f/src/couch_replicator/src/couch_replicator_scheduler.erl#L238)). 

## Expected Behavior

`[replicator]max_history` to be added to `config/replicator.rst` as a configurable parameter for the replicator database (e.g. https://docs.couchdb.org/en/latest/config/replicator.html#replicator/max_history).

## Current Behavior

`[replicator]max_history` is not documented in `config/replicator.rst`.

## Possible Solution

Add `max_history` to `config/replicator.rst`, including brief explanation and default value `20` (see [`couch_replicator_scheduler#L77`](https://github.com/apache/couchdb/blob/3.1.0/src/couch_replicator/src/couch_replicator_scheduler.erl#L77)).

## Steps to Reproduce (for bugs)

N/A.

## Context

Experimenting with CouchDB in environments of low and/or intermittent connectivity, where it is important that replication restarts quickly when network connectivity is established. One of the possible solutions is detailed in an issue in the main repo [here](https://github.com/apache/couchdb/issues/1399), which references configurable parameters `[replicator]retries_per_request` and `[replicator]max_history` as a potential solution to this problem.

## Your Environment

* Version used: `v3.1.0`.
* Browser Name and version: Brave 1.8.95.
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS.
* Link to your project: https://github.com/wlthomson/ocsupply.

**Comment by janl** [comment]
@wlthomson wanna open a PR for this?

**Comment by wlthomson** [comment]
@janl Sure, will do!
