### ISSUE TITLE
jwt_authentication_handler missing in docs

### ISSUE THREAD

**Issue by hadrysmateusz** [apache/couchdb-documentation#562]
I'm very new to couchdb so I might be missing something obvious, but I think that the [authentication handlers](https://docs.couchdb.org/en/stable/config/http.html#chttpd/authentication_handlers) section of the configuration docs is missing the {chttpd_auth, jwt_authentication_handler} option which is present in the [authentication section](https://docs.couchdb.org/en/stable/api/server/authn.html#authentication) of the docs.

![image](https://user-images.githubusercontent.com/26979471/86173855-f01cfa80-bb20-11ea-8b6e-ba269b6946df.png)

**Comment by wohali** [comment]
You are correct; all we have right now is [this section](https://docs.couchdb.org/en/latest/api/server/authn.html?highlight=jwt#jwt-authentication) and a note in the release notes.

A pull request to add it would be most welcome!

**Comment by hadrysmateusz** [comment]
Sure, here's the PR #563
