### ISSUE TITLE
1.3.18. /db/_purge response model seems to be wrong in the documentation

### ISSUE THREAD

**Issue by Dev-Owl** [apache/couchdb-documentation#571]
## Expected Behavior
I would expect to get the response as described in the documentation. The response from my fresh setup doesn't contain the second "purged" property that is mentioned in the [documentation](https://docs.couchdb.org/en/latest/api/database/misc.html?highlight=purge#db-purge):
````json
{
	"purge_seq": null,
	"purged": {
		"c6114c65e295552ab1019e2b046b10e": {
			"purged": [
				"3-c50a32451890a3f1c3e423334cc92745"
			]
		}
	}
}
````
Either the code needs an update or the documentation or I got something wrong while testing/reading about this feature.

## Current Behavior
As mentioned above, the below response is missing the second purged property inside the JSON:

````json
{
	"purge_seq": null,
	"purged": {
		"c6114c65e295552ab1019e2b046b10e": [
			"3-c50a32451890a3f1c3e423334cc92745"
		]
	}
}
````

## Steps to Reproduce (for bugs)
1. Create a document
2. Purge the document with it ID and current revision (or a list of revisions) 
3. The response structure will be different as noted in the documentation

## Context
Found while writing test cases for my Couch .net core client, changed the model to match the actual response and completed the unit test successfully 

## Your Environment
* Version used: 3.10
* Browser Name and version: NA
* Operating System and version (desktop or mobile): Found on Windows 10 
* Link to your project: https://github.com/Dev-Owl/pillowsharp

**Comment by janl** [comment]
yup, that looks like an honest mistake in the docs. Wanna try and provide a PR?

**Comment by Dev-Owl** [comment]
Sure, just send the PR
