### ISSUE TITLE
MacOS installation guide download link is incorrect

### ISSUE THREAD

**Issue by personalnadir** [apache/couchdb-documentation#619]
Under heading 1.3.1  [Installation using the Apache CouchDB native application](https://docs.couchdb.org/en/stable/install/mac.html#installation-using-the-apache-couchdb-native-application) bullet 1 has a link labelled 'Download Apache CouchDB for macOS.' This links to http://couchdb.org/#download, which brings up a German page saying 'unknown domain'. 

## Expected Behavior
The link opens a page with MacOS downloads. 

## Current Behavior
The link currently points to http://couchdb.org/#download, which brings up a German page saying 'unknown domain'. 

## Possible Solution
Change the link to https://couchdb.apache.org/#download

## Steps to Reproduce (for bugs)
1. Visit https://docs.couchdb.org/en/stable/install/mac.html#installation-using-the-apache-couchdb-native-application
2. Click link labelled 'Download Apache CouchDB for macOS.'

## Context
I was reading the installation guide and expected the link to start a download of the current stable release of CouchDB for MacOS

## Your Environment
* Browser Name and version: Firefox and Safari
* Operating System and version (desktop or mobile): Desktop MacOS

**Comment by ddadon10** [comment]
I would like to add the download link is also dead in the homepage, at https://docs.couchdb.org/en/stable/index.html

**Comment by wohali** [comment]
I've got this.
