### ISSUE TITLE
Remove partial filter selector field from POST /{db}/_index query parameters list

### ISSUE THREAD

**Issue by emlaver** [apache/couchdb-documentation#625]
## Expected Behavior
When using partial indexes, the `partial_filter_selector` object is to be added within the `index` object.  Example of a partial index creation in https://docs.couchdb.org/en/stable/api/database/find.html#partial-indexes.

## Current Behavior
The `partial_filter_selector` field is listed along side `index` and other fields in the [POST /db/_index query param list](https://docs.couchdb.org/en/stable/api/database/find.html#post--db-_index).  

## Possible Solution
- Remove the reference of `partial_filter_selector` field in the POST /{db}/_index query parameters list. 
- Move the query param description of `partial_filter_selector` to the `index` description.

## Steps to Reproduce (for bugs)

If you try to create an index with `partial_filter_selector` along side `index` you'll get an error: `Invalid key partial_filter_selector for this request`.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by wohali** [comment]
This is already fixed in https://docs.couchdb.org/en/latest/api/database/find.html#post--db-_index .
