### ISSUE TITLE
Document query_response option

### ISSUE THREAD

**Issue by tkoeppen** [apache/couchdb-documentation#628]
## Description

When querying all documents from a database it happens that the http client is not telling that not all data could be read from the database.

We send the same request several times a day and response contains nearly always the expected 10k documents.

From time to time (every other week) the a response for the same query contains e.g. only 8k documents instead of expected 10k.
When this happen we see in couchdb.log the message "aborted" and short after the error "timeout".

The couchdb contains approx. 100 database, but it happens from time to time for 3 different databases only.
The affected databases contain each approx. 10k docs (1 doc approx. 3k bytes)

We run the same application in multiple environments but find this behaviour in one environment only.
We can run thousands of the same request and it does not happen for multiple days.

This happen in a clustered couchdb.

## Steps to Reproduce

We cannot reproduce this issue systematically. 
We send a request like 
curl "http://[user]:[pw]@localhost/database1/_all_docs?include_docs=true

Every other week (not at a specific time) we find in couchdb.log the related error.

We are not sure how to further trace the "aborted" symptom inside couchdb, eventually we add trace to the go-driver to figure out more and to decide if that is a couchdb issue or client driver issue.

## Expected Behaviour

1. The response should always contain all documents without stopping in the middle of the response.
2. When couchdb query run into "aborted" wouldn't it be better when the http response status is http-500 instead of http-200? (so in our case the go-driver can handle the error)

## Your Environment

```
{
  "couchdb": "Welcome",
  "version": "3.1.0",
  "git_sha": "ff0feea20",
  "uuid": "5efc7bd500f26ded5b4119e82fa659cc",
  "features": [
    "access-ready",
    "partitioned",
    "pluggable-storage-engines",
    "reshard",
    "scheduler"
  ],
  "vendor": {
    "name": "The Apache Software Foundation"
  }
}
```

* CouchDB version used: 3.1.0
* Browser name and version: Not applicable
* Operating system and version: couchdb-docker on CentOS 7

## Additional Context

We upgraded to 3.1.0 short after it was released but cannot prove if we saw this behaviour only since then.
At the time where it happen no other unusual errors or activities has been seen in couchdb.log.
cpu/memory also do not show major anomalies.

Lines from couchdb.log

```
[notice] 2020-07-23T03:00:45.960786Z couchdb@x.x.x.x <0.10328.1588> 3ece2982af couchdb-service:5984 1.2.3.4 user GET /database1/_all_docs?include_docs=true 200 aborted 17983
[error] 2020-07-23T03:00:45.960831Z couchdb@x.x.x.x <0.10328.1588> 3ece2982af Response abnormally terminated: timeout

[notice] 2020-08-04T03:00:30.455723Z couchdb@x.x.x.x <0.4075.5619> 9f5b0c41b5 couchdb-service:5984 1.2.3.4 user GET /database2/_all_docs?include_docs=true 200 aborted 20067
[error] 2020-08-04T03:00:30.455758Z couchdb@x.x.x.x <0.4075.5619> 9f5b0c41b5 Response abnormally terminated: timeout
```

**Comment by wohali** [comment]
FYI this is also available as a server-wide configuration, `[chttpd] buffer_response`.
