### ISSUE TITLE
Documentation on 3.1.1 version includes `$keyMapMatch` operator, which is missing in tag version.

### ISSUE THREAD

**Issue by javierg** [apache/couchdb-documentation#632]
`$KeyMapMatch` operator included in docs for 3.1.1 is actually missing.

## Expected Behavior
Documentation for 3.1.1 should not include `$keyMapMatch` operator, as it is not available on 3.1.1

## Steps to Reproduce (for bugs)

After reading docs on latest version on web I come across `$keyMapMatch` operator. But on trying a query that fails with `invalid_operator`, I lookup on the Github repo to see when this was available. I can see the code for the operator is in `main` branch and on `3.x` branch, bit it is not on `3.1.1` tag, which I asume is the one distributed on the binary download.
Also, looking on docs on the downloaded binary includes the documentation for the operator, but the code is also missing.

## Context
Upon finding this nice feature that it will help a lot with moving some JS views to Mango queries, It was frustrating debugging why the feature that documents show will not work. 

## Your Environment
* Version used: 3.1.1
* Browser Name and version: Chrome Version 89.0.4389.90 
* Operating System and version (desktop or mobile): OSX 10.15.4

**Comment by wohali** [comment]
@javierg Thanks for the report.

We're gearing up for the 3.2 release, so I think we'll just make this a Known Issue for the 3.1.1 docs... as pulling it out of the 3.1.1 docs is going to be a pain.

Hopefully, you'll have a new release with `keyMapMatch` soon!
