### ISSUE TITLE
Broken links (and problably travis build) because they are pointing to old master branch

### ISSUE THREAD

**Issue by binary-sequence** [apache/couchdb-documentation#664]
Example: https://docs.couchdb.org/en/stable/replication/protocol.html#replication-protocol-algorithm

couch_replicator -> https://github.com/apache/couchdb/tree/master/src/couch_replicator

**Comment by wohali** [comment]
Fixed in the `latest` version - `stable` will not update until CouchDB 3.2 is released (which is imminent).
