### ISSUE TITLE
Broken links on Installation pages

### ISSUE THREAD

**Issue by dianabarsan** [apache/couchdb-documentation#671]
Links found on https://docs.couchdb.org/en/stable/install/mac.html and https://docs.couchdb.org/en/stable/install/mac.html that point to http://couchdb.org/ take you to a uberspace.de default page. 

![image](https://user-images.githubusercontent.com/35681649/126631245-0e5eeb92-a362-4032-bdde-a125aeb2035e.png)

## Expected Behavior
Links on install pages should work. 

## Possible Solution
It looks like the correct links should point to http://couchdb.apache.org instead.

**Comment by wohali** [comment]
Paging @janl

**Comment by wohali** [comment]
This is already fixed on https://docs.couchdb.org/en/latest/install/mac.html . We can't easily change the `stable` link due to Apache workflow process.

When CouchDB 3.2 releases, the link will update.
