### ISSUE TITLE
Fix timeout time-unit (milliseconds instead of seconds) in /_db_updates doc page

### ISSUE THREAD

**Issue by arifcse019** [apache/couchdb-documentation#676]
## Expected Behavior

The documentation page https://docs.couchdb.org/en/latest/api/server/common.html#db-updates should correctly specify the time-unit for the timeout setting. The API expects a number in milliseconds but the documentation says the number should be in seconds

## Current Behavior

The documentation on this page https://docs.couchdb.org/en/latest/api/server/common.html#db-updates states that the timeout setting is in seconds. But actually, the API expects it in milliseconds (I have tested it in our setup)

```
$ time curl -u <username> 'https://<couch-url>/_db_updates?feed=continuous&timeout=5000&since=now'
{"last_seq":"4795109-<long-string>"}


real	0m5.438s
user	0m0.024s
sys	0m0.008s
```

## Possible Solution

Update Line 471-472 in https://github.com/apache/couchdb-documentation/blob/main/src/api/server/common.rst from 

> :query number timeout: Number of seconds until CouchDB closes the
>       connection. Default is ``60``

 to

>     :query number timeout: Number of milliseconds until CouchDB closes the
>     connection. Default is ``60000``

## Steps to Reproduce (for bugs)

```
$ time curl -u <username> 'https://<couch-url>/_db_updates?feed=continuous&timeout=5000&since=now'
{"last_seq":"4795109-<long-string>"}


real	0m5.438s
user	0m0.024s
sys	0m0.008s
```

```
$ time curl -u <username> 'https://<couch-url>/_db_updates?feed=continuous&timeout=70&since=now'
{"last_seq":"4786723-<long-string>"}


real	0m0.463s
user	0m0.021s
sys	0m0.015s
```

## Context

We use db_updates feed to process changes made in our client databases. And the documentation confuses us what value to use in the timeout setting

## Your Environment

* Version used: 2.1.2
* Browser Name and version: curl
* Operating System and version (desktop or mobile): OSx 11.2.3 desktop
* Link to your project: N/A

**Comment by big-r81** [comment]
Thank you 🙏
