### ISSUE TITLE
I can't update couch-db via sudo apt-get update in Debain 10, I got 403 forbidden error message!

### ISSUE THREAD

**Issue by Navid61** [apache/couchdb-documentation#678]
I'm trying to get new update for couch-db on my Debian 10 OS, but I got this error

Err:11 https://apache.bintray.com/couchdb-deb buster InRelease                 
  403  Forbidden [IP: 52.40.65.167 443]
Hit:12 https://apache.jfrog.io/artifactory/couchdb-deb buster InRelease
Reading package lists... Done
E: Failed to fetch https://apache.bintray.com/couchdb-deb/dists/buster/InRelease  403  Forbidden [IP: 52.40.65.167 443]
E: The repository 'https://apache.bintray.com/couchdb-deb buster InRelease' is no longer signed.
## Expected Behavior
I'd expect it'll get new probability updates

## Current Behavior
I got error   403  Forbidden [IP: 52.40.65.167 443]

## Possible Solution
I did try fix that issue via tor by network, torify command similar to this: sudo torify apt-get update

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
i can not get new updates for couch-db

## Your Environment
Debian 10.10
I'm using terminal my shell is zsh (oh-my-zsh)

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by nickva** [comment]
> Err:11 https://apache.bintray.com/couchdb-deb buster InRelease

Bintray is no longer supported. Remove the bintray repository source and use only the jfrog one:

https://docs.couchdb.org/en/stable/install/unix.html#enabling-the-apache-couchdb-package-repository

**Comment by 842Mono** [comment]
So many articles need to be updated.
