### ISSUE TITLE
Couchdb repository is forbidden.

### ISSUE THREAD

**Issue by thorvaldhrafn** [apache/couchdb-documentation#680]
Couchdb repository does not work. Access is forbidden.

## Expected Behavior
Trying to update packages in Ubuntu 20.04
apt update
...
Reading package lists... Done
Building dependency tree       
Reading state information... Done

## Current Behavior
apt update
....
Err:10 https://apache.bintray.com/couchdb-deb focal InRelease             
  403  Forbidden [IP: 54.148.26.147 443]
Reading package lists... Done                       
E: Failed to fetch https://apache.bintray.com/couchdb-deb/dists/focal/InRelease  403  Forbidden [IP: 54.148.26.147 443]
E: The repository 'https://apache.bintray.com/couchdb-deb focal InRelease' is not signed.

## Your Environment

cat /etc/issue
Ubuntu 20.04.3 LTS \n \l
uname -r
5.4.0-73-generic

**Comment by nickva** [comment]
bintray.com support was discontinued, unfortunately.

Please use the jfrog repository as described here https://docs.couchdb.org/en/latest/install/unix.html
