### ISSUE TITLE
Linux installation information is incorrect - bintray.com service has been shut down by JFrog

### ISSUE THREAD

**Issue by NetAppBlueDevil** [apache/couchdb-documentation#681]
The installation documentation  couchdb-documentation/src/install/unix.rst still references apache.bintray.com as the source of apt/yum repos.  This service no longer is provided by JFrog.  I don't know where apache moved the hosting of these linux repos, but the documentation needs to be updated to reflect the changes made in response to the bintray shutdown.

**Comment by wohali** [comment]
Documentation has been updated, see https://docs.couchdb.org/en/stable/install/unix.html and  the contents of this repo.
