### ISSUE TITLE
no progress field when GET /_active_tasks HTTP/1.1 

### ISSUE THREAD

**Issue by guanfeix** [apache/couchdb-documentation#701]
j just migrate my application from 1.6.1 to 2.3.1 find my couchdb GET /_active_tasks HTTP/1.1 no process field as telled in the document, so any guys can tell me how to know couchdb sync state  in a timepoint, in the  past i just use process field.
![image](https://user-images.githubusercontent.com/34960209/143202007-6c76833f-c080-4b4a-9cc7-73f722bbc25c.png)
2.3.1
![image](https://user-images.githubusercontent.com/34960209/143202885-78052e4f-5145-44e8-bd1f-27bf335e2abd.png)

1.6.1
![image](https://user-images.githubusercontent.com/34960209/143202668-8e404cf8-c8e3-4380-ba76-aafb9d832d3c.png)

**Comment by nickva** [comment]
Thanks for the report. It looks like the documentation examples were not updated.

Also, I assume you meant `no progress field` instead of `no process field` as the issue states. As there is technically a process field - `"pid"`.

Progress can be estimated using the `changes_pending` metric.

**Comment by guanfeix** [comment]
> technically
thanks you much,i can judge the replication state by changes_pending,  but the progress seems no method to estimate without fields like total_changes or changes_done. 
Also I have question for value of some active_tasks changes_pending which  is null rather than 0,means no changes transmit in last replicate? wht;s the difference between 0 and null.
In the last the pid field's value look like strange like 0.7307.984.

**Comment by nickva** [comment]
I believe `null` means it hasn't been computed it yet. There is a periodic process which every few seconds calls `_changes?limit=0&since=Seq`  to estimate the number of pending changes. 0 means there are 0 pending changes. `changes_done` I believe is now `"revisions_checked"`. There are more detailed stats regarding how many revisions were missing and how many document writes or doc failures happened.

The `pid` is the Erlang process ID which handles the replication. It's a low level detail that can be useful if you use the remote shell (remsh) and want to get detailed process stats about the replication process, or say, want to kill it and restart it. The 3-integers is just how Erlang identifies its processes.

**Comment by guanfeix** [comment]
@nickva  is there any relationshiop between erlang:system_info(port_limit). and ERL_MAX_PORTS,which the document say default 1024 but i see is 65536(linux port numbers).If not how can i figure out the real maximum connections which erlang  allowd
![图片](https://user-images.githubusercontent.com/34960209/158329378-3b0be452-e884-42be-98da-1ebd78549b56.png)

![图片](https://user-images.githubusercontent.com/34960209/158329305-8dfe0383-8190-4781-9d10-4137881f7280.png)

**Comment by guanfeix** [comment]
@nickva I have also one question of views compaction.
how do i should do it, the designname means what. I try methods below,which all not work.
curl -H "Content-Type: application/json" -X POST http://localhost:5984/dbname/_compact/designname
curl -H "Content-Type: application/json" -X POST http://localhost:5984/dpl_job/_compact/by_type  
curl -H "Content-Type: application/json" -X POST http://localhost:5984/dpl_job/_compact/_design/dpl_job
![Uploading 图片.png…]()

**Comment by nickva** [comment]
@guanfeix port_limit is probably the next power of 2 based on ERL_MAX_PORTS


At least on Erlang 23:


```
ERL_MAX_PORTS=1042 erl
Erlang/OTP 23 [erts-11.2.2.9] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Eshell V11.2.2.9  (abort with ^G)
1> erlang:system_info(port_limit).
2048
```

```
ERL_MAX_PORTS=3000 erl
Erlang/OTP 23 [erts-11.2.2.9] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Eshell V11.2.2.9  (abort with ^G)
1> erlang:system_info(port_limit).
4096
```

```
ERL_MAX_PORTS=9000 erl
Erlang/OTP 23 [erts-11.2.2.9] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Eshell V11.2.2.9  (abort with ^G)
1> erlang:system_info(port_limit).
16384
```

**Comment by nickva** [comment]
@guanfeix `designname` is for compacting the views. There are two types of compactions - main database compaction, and view compaction. 

https://docs.couchdb.org/en/stable/maintenance/compaction.html#manual-view-compaction

**Comment by nickva** [comment]
Also, I think we should close this ticket :-) as the discussion doesn't seem to be relevant to the active_task as much as the initial comments go.

**Comment by guanfeix** [comment]
Ok,thanks a lot i real helpful for me. In the last can you take one detailed example for designname about  views comapction.I just  can't find the right field this even after I look up the document carefully.

curl -H "Content-Type: application/json" -X POST http://localhost:5984/dbname/_compact/designname
